[package]
name = "uplc-wasm"
version = "0.2.0"
edition = "2021"
description = "A WebAssembly (wasm) wrapper for the uplc crate"
repository = "https://github.com/mpizenberg/uplc-wasm"
license = "Apache-2.0"
keywords = ["cardano", "wasm", "uplc"]
categories = ["algorithms"]

[lib]
crate-type = ["cdylib"]

[dependencies]
uplc = "1.1.19"
wasm-bindgen = "0.2.93"
js-sys = "0.3.70"
wee_alloc = "0.4.5"
# required for wasm usage of getrandom
getrandom = { version = "0.2", features = ["js"] }

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Oz']
